export const influencers = [
    {
        id: 1,
        name: "Aldous Copaland",
        image: "https://randomuser.me/api/portraits/men/1.jpg",
        likes: 1000,
        interests: ["family", "cinema", "news"],
        description: "aldous * 28 years",
        subscribers: 40000,
        postsPerMonth: 30,
        averageViews: 10000,
        averageLikes: 2000,
        likesFromSubscribers: 60, // percentage
        reachPrice: "1000",
        cpmw: "$10",
        verified: true,
    },
    {
        id: 2,
        name: "Lady Gaga",
        image: "https://randomuser.me/api/portraits/women/3.jpg",
        likes: 1200,
        interests: ["family", "cinema", "news"],
        description: "aldous * 28 years",
        subscribers: 50000,
        postsPerMonth: 30,
        averageViews: 10000,
        averageLikes: 2000,
        likesFromSubscribers: 60, // percentage
        reachPrice: "2000",
        cpmw: "$10",
        verified: false,
    },
    {
        id: 3,
        name: "John Cena",
        image: "https://randomuser.me/api/portraits/men/4.jpg",
        likes: 1400,
        interests: ["family", "cinema", "news"],
        description: "aldous * 28 years",
        subscribers: 60000,
        postsPerMonth: 30,
        averageViews: 10000,
        averageLikes: 2000,
        likesFromSubscribers: 60, // percentage
        reachPrice: "3000",
        cpmw: "$10",
        verified: true,
    },
];